name: roblox-win-installer

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  name:
    runs-on: windows-latest
    steps:
      - name: install roblox
        uses: actions/checkout@v1
        run: |
          pip install wget psutil
          python install.py "${{ secrets.ROBLOSECURITY }}"
      - name: download run-in-roblox
        run: Invoke-WebRequest "https://github.com/OrbitalOwen/run-in-roblox/releases/download/0.2.0/run-in-roblox.exe" -OutFile run-in-roblox.exe
      - name: use run-in-roblox
        run: |
          "print('hi')" | Out-File test.lua
          run-in-roblox.exe -t 600 .\test.lua
