name: roblox-win-installer

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    name:
        runs-on: windows-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v1
            - run: pip install -r requirements.txt
            - run: python install.py "${{ secrets.ROBLOSECURITY }}"
